# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bd < Formula
  desc "AI-supervised issue tracker for coding workflows"
  homepage "https://github.com/steveyegge/beads"
  version "0.21.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveyegge/beads/releases/download/v0.21.9/beads_0.21.9_darwin_amd64.tar.gz"
      sha256 "136cb5b5c53bf844b83174df3c95abe504a32584231130b400e5272f13bb356e"

      def install
        bin.install "bd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveyegge/beads/releases/download/v0.21.9/beads_0.21.9_darwin_arm64.tar.gz"
      sha256 "fec19c750bfae9ba5a7bfb05b4711831b54696371168d8a097d20cb32dbd486c"

      def install
        bin.install "bd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveyegge/beads/releases/download/v0.21.9/beads_0.21.9_linux_amd64.tar.gz"
      sha256 "f695c58e192902c4c39a3ed2e3c303524a387db55a41994cfc258f0f78e631c3"
      def install
        bin.install "bd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveyegge/beads/releases/download/v0.21.9/beads_0.21.9_linux_arm64.tar.gz"
      sha256 "e1abebe6e0923bf4dbe42f46b05fe6e71711cb834568797b135055fc42ba89c9"
      def install
        bin.install "bd"
      end
    end
  end

  test do
    system "#{bin}/bd", "version"
  end
end
